### ISSUE TITLE
Issues with events

### ISSUE THREAD

**Issue by goDawgs18** [klavinslab/enviro#4]
I am trying to use the 'keydown' and 'keyup' events in my project to get user input but I cannot get them to work properly. In my test code I am trying to print something when an event occurs. 

The following code is inside the controller 
```
class WandererController : public StateMachine, public AgentInterface {
void init() {
            watch("connection", [&](Event& e) {
                std::cout << "connection made " << "\n";
            });
            watch("key_down", [&](Event& e) {
                std::cout << "button released with value: " << e.value()["key"]  << "\n";
            });
            watch("keyup", [&](Event& e) {
                std::cout << "button click with value: " << e.value()["key"]  << "\n";
            });
            watch("screen_click", [&](Event& e) {
              std::cout << "clicked screen at " << e.value()["x"] << ", " << e.value()["y"] << "\n";
            });
            watch("agent_click", [&](Event& e) {
              std::cout << "agent clicked id : " << e.value()["id"]  << "loc: "<< e.value()["x"] << ", " << e.value()["y"] << "\n";
            });
        }
//other stuff below
}
```

Then when I go to my local host, refresh my page, click on the screen, click on agents, and press buttons on my keyboard I get the following out of my terminal window

```
root@f23192b9c18a:/source/week_9# enviro
Listening on port 8765
agent clicked id : 0loc: -4.501858711242676, -3.8020811080932617
clicked screen at 288.001708984375, 47.697914123535156
```

Any help would be appreciated.
Thanks

**Comment by klavins** [comment]
The event should be keydown not key_down for one thing.

**Comment by goDawgs18** [comment]
Sorry, for the mistake. I just corrected it, to keydown instead of key_down. I still am not getting any print statements though.

**Comment by goDawgs18** [comment]
Solved [in this post](https://github.com/klavinslab/enviro/issues/5)

Resolution pasted here:

Okay thank you, for now my issues are resolved. I was running this to start up my docker image when I needed:

docker run -p80:80 -p8765:8765 -v $PWD:/source -it klavins/enviro:v1.1 bash

When I needed to be running this:
docker run -p80:80 -p8765:8765 -v $PWD:/source -it klavins/enviro:v1.6 bash
